# Generated by Django 6.0.6 on 2026-06-12 06:25

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name=django.db.models.fields.DateField),
        ),
    ]
