# Generated by Django 6.0.6 on 2026-06-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_add_bookimage'),
        ('books', '0006_add_password_reset_token'),
    ]

    operations = [
    ]
