# Generated by Django 6.0.6 on 2026-07-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_add_transaction_uuid_and_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='covers/thumbs/'),
        ),
    ]
